apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-vault-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: hashicorp-vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: GROQ_API_KEY
      remoteRef:
        key: secret/data/stern-watch/production
        property: GROQ_API_KEY
    - secretKey: NEO4J_PASSWORD
      remoteRef:
        key: secret/data/stern-watch/production
        property: NEO4J_PASSWORD