FROM apache/airflow:2.8.2-python3.11

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq-dev build-essential \
    && rm -rf /var/lib/apt/lists/*

USER airflow

COPY pyproject.toml /opt/airflow/
RUN pip install --no-cache-dir -e .